# Generated by Django 5.2.9 on 2025-12-15 04:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_environmentaldata_additional_info_and_more'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='professional_profiles/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('specialty', models.CharField(choices=[('agronomist', 'Agronomist'), ('veterinarian', 'Veterinarian'), ('mechanic', 'Mechanic'), ('chemist', 'Chemist'), ('farm_manager', 'Farm Manager'), ('agricultural_engineer', 'Agricultural Engineer'), ('soil_scientist', 'Soil Scientist'), ('crop_consultant', 'Crop Consultant'), ('pest_control', 'Pest Control Specialist'), ('livestock_handler', 'Livestock Handler'), ('irrigation_specialist', 'Irrigation Specialist'), ('agricultural_economist', 'Agricultural Economist'), ('horticulturist', 'Horticulturist'), ('agricultural_technician', 'Agricultural Technician'), ('food_safety', 'Food Safety Specialist'), ('data_analyst', 'Agricultural Data Analyst'), ('farm_laborer', 'Farm Laborer'), ('equipment_operator', 'Equipment Operator'), ('harvester', 'Harvester'), ('planting_specialist', 'Planting Specialist')], max_length=50)),
                ('years_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('seasonal', 'Seasonal'), ('available', 'Available Now'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('education', models.TextField(blank=True, help_text='Educational background')),
                ('work_experience', models.TextField(blank=True, help_text='Detailed work experience')),
                ('skills', models.JSONField(default=list, help_text='List of skills')),
                ('certifications', models.JSONField(default=list, help_text='List of certifications')),
                ('languages', models.JSONField(default=list, help_text='Languages spoken')),
                ('notable_projects', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('response_time', models.CharField(default='Within 24 hours', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-featured', '-average_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('specialty_required', models.CharField(choices=[('agronomist', 'Agronomist'), ('veterinarian', 'Veterinarian'), ('mechanic', 'Mechanic'), ('chemist', 'Chemist'), ('farm_manager', 'Farm Manager'), ('agricultural_engineer', 'Agricultural Engineer'), ('soil_scientist', 'Soil Scientist'), ('crop_consultant', 'Crop Consultant'), ('pest_control', 'Pest Control Specialist'), ('livestock_handler', 'Livestock Handler'), ('irrigation_specialist', 'Irrigation Specialist'), ('agricultural_economist', 'Agricultural Economist'), ('horticulturist', 'Horticulturist'), ('agricultural_technician', 'Agricultural Technician'), ('food_safety', 'Food Safety Specialist'), ('data_analyst', 'Agricultural Data Analyst'), ('farm_laborer', 'Farm Laborer'), ('equipment_operator', 'Equipment Operator'), ('harvester', 'Harvester'), ('planting_specialist', 'Planting Specialist')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price'), ('daily', 'Daily Rate')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('experience_required', models.IntegerField(default=0)),
                ('skills_required', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='farms.farm')),
                ('hired_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_jobs', to='workforce.professionalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_start', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workforce.jobposting')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='workforce.professionalprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('work_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False, help_text='Verified purchase/hire')),
                ('helpful_count', models.IntegerField(default=0)),
                ('response', models.TextField(blank=True, help_text="Professional's response to review")),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workforce.professionalprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['specialty', 'location'], name='workforce_p_special_676ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['availability', 'is_active'], name='workforce_p_availab_ebc485_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'professional')},
        ),
        migrations.AlterUniqueTogether(
            name='professionalreview',
            unique_together={('professional', 'reviewer')},
        ),
    ]
