# Generated by Django 5.2.8 on 2026-06-12 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0002_paymenttransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("momo", "Mobile Money"), ("bank", "Bank")],
                        default="momo",
                        max_length=10,
                    ),
                ),
                (
                    "account_bank",
                    models.CharField(
                        default="MPS",
                        help_text='"MPS" for mobile money, or a bank code for bank payouts',
                        max_length=20,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Mobile number (international format) for MoMo, or bank account number",
                        max_length=40,
                    ),
                ),
                ("account_name", models.CharField(max_length=120)),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        help_text="MTN or AIRTEL (mobile money only)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
