# Generated by Django 5.2.8 on 2026-06-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0003_payoutaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrow",
            name="delivered_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="delivery_otp",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="escrow",
            name="dispute_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrow",
            name="dispute_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="escrow",
            name="otp_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
