# Generated by Django 5.2.8 on 2026-06-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0004_escrow_delivered_confirmed_at_escrow_delivery_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrow",
            name="dispatch_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="escrow",
            name="dispatch_photo",
            field=models.ImageField(blank=True, null=True, upload_to="trade_proof/"),
        ),
        migrations.AddField(
            model_name="escrow",
            name="dispatch_quantity",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="escrow",
            name="dispute_photo",
            field=models.ImageField(blank=True, null=True, upload_to="trade_proof/"),
        ),
        migrations.AddField(
            model_name="escrow",
            name="dispute_quantity",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
