# Generated by Django 5.2.8 on 2025-12-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0001_initial"),
        ("farms", "0004_alter_environmentaldata_additional_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("planting_method", models.CharField(blank=True, max_length=50)),
                ("planting_date", models.DateField()),
                ("expected_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50)),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="crop",
            name="field",
        ),
        migrations.RemoveField(
            model_name="croptask",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="cropexpense",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="cropemployeeassignment",
            name="crop_task",
        ),
        migrations.RemoveField(
            model_name="cropemployeeassignment",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="cropexpense",
            name="purchased_by",
        ),
        migrations.RemoveField(
            model_name="cropexpense",
            name="receipt_attachment",
        ),
        migrations.CreateModel(
            name="CropEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("planting", "Planting"),
                            ("fertilizer", "Fertilizer Application"),
                            ("irrigation", "Irrigation"),
                            ("pesticide", "Pesticide/Herbicide"),
                            ("mulching", "Mulching"),
                            ("germination", "Germination Observation"),
                            ("growth", "Growth Stage"),
                            ("pest", "Pest/Disease Observation"),
                            ("stress", "Stress Event"),
                            ("harvest", "Harvest"),
                            ("loss", "Crop Failure/Loss"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropcycle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=255)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("field", "Field/Plot"),
                            ("bed", "Bed/Plot"),
                            ("greenhouse", "Greenhouse/Block"),
                            ("orchard", "Orchard Block"),
                            ("hydroponic", "Hydroponic System/Channel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in ha/acres/m²",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farms.field",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cropcycle",
            name="crop_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crops.cropunit"
            ),
        ),
        migrations.CreateModel(
            name="HarvestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("harvest_date", models.DateField()),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                (
                    "quality_grade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropcycle",
                    ),
                ),
            ],
        ),
    ]
