# Generated by Django 5.2.8 on 2025-12-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_ailog_animal_ailog_confidence_ailog_explanation_and_more"),
        ("crops", "0002_cropcycle_remove_crop_field_remove_croptask_crop_and_more"),
        (
            "inventory",
            "0002_inventory_animal_inventory_date_inventory_item_type_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Crop",
        ),
        migrations.DeleteModel(
            name="CropTask",
        ),
        migrations.DeleteModel(
            name="CropEmployeeAssignment",
        ),
        migrations.DeleteModel(
            name="CropExpense",
        ),
    ]
