# Generated by Django 5.2.8 on 2025-12-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0003_delete_crop_delete_croptask_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cropcycle",
            name="area",
        ),
        migrations.RemoveField(
            model_name="cropunit",
            name="area",
        ),
    ]
