# Generated by Django 5.2.8 on 2026-06-18 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0005_escrow_dispatch_note_escrow_dispatch_photo_and_more"),
        ("logistics", "0001_initial"),
        ("marketplace", "0010_order_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("boda", "Boda boda (motorcycle)"),
                            ("pickup", "Pickup"),
                            ("truck", "Truck"),
                            ("taxi", "Taxi / van"),
                            ("bicycle", "Bicycle"),
                        ],
                        default="boda",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "national_id",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "service_area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Districts/areas served",
                        max_length=160,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                (
                    "deposit_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deposit_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="transporters/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transporter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type_required",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "pickup_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "drop_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "offered_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open (awaiting a rider)"),
                            ("accepted", "Accepted"),
                            ("picked_up", "Picked up"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("pickup_code", models.CharField(blank=True, default="", max_length=8)),
                ("notes", models.TextField(blank=True, default="")),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_delivery_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_jobs",
                        to="escrow.escrow",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_job",
                        to="marketplace.order",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="logistics.transporter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransporterReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transporter_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.order",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="logistics.transporter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
