# Generated by Django 5.2.8 on 2026-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_transporter_deliveryjob_transporterreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="access_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="deliveryjob",
            name="access_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="deliveryjob",
            name="access_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
