# Generated by Django 5.2.9 on 2025-12-12 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='last_visited',
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_data', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size_unit',
            field=models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('square_meters', 'Square Meters')], default='acres', max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='type',
            field=models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('mixed', 'Mixed')], default='crops', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='field',
            name='purpose',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='field',
            name='size_unit',
            field=models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('square_meters', 'Square Meters')], default='acres', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
