# Generated by Django 5.2.9 on 2025-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_remove_farm_last_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='total_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
