# Generated by Django 5.2.8 on 2025-12-21 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("farms", "0004_alter_environmentaldata_additional_info_and_more"),
        ("livestock", "0002_remove_livestockunit_animal_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailog",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="livestock.animal",
            ),
        ),
        migrations.AddField(
            model_name="ailog",
            name="confidence",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="ailog",
            name="explanation",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="ailog",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="ailog",
            name="generated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ailog",
            name="inputs",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="ailog",
            name="livestock_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="livestock.livestockunit",
            ),
        ),
        migrations.AddField(
            model_name="ailog",
            name="prediction_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="ailog",
            name="result",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="Prediction",
        ),
    ]
