# Generated by Django 5.2.9 on 2026-06-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0011_store_banner_store_business_hours_store_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PesapalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant_ref", models.CharField(max_length=100, unique=True)),
                (
                    "order_tracking_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                            ("INVALID", "Invalid"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("redirect_url", models.URLField(blank=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesapal_payments",
                        to="marketplace.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
