# Generated by Django 5.2.9 on 2025-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('retailer', 'Retailer / Buyer'), ('specialized', 'Specialized Professional')], max_length=20, null=True),
        ),
    ]
