# Generated by Django 5.2.9 on 2025-12-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedprofessional',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='professional_profiles/'),
        ),
        migrations.AddField(
            model_name='specializedprofessional',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading: provide image URL', null=True),
        ),
    ]
