# Generated by Django 5.2.8 on 2026-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_specializedprofessional_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("farmer", "Farmer"),
                    ("retailer", "Retailer / Buyer"),
                    ("specialized", "Specialized Professional"),
                    ("transporter", "Transporter"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
