# Generated by Django 5.2.8 on 2026-06-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity", models.CharField(max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("export", "Export"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("unit", models.CharField(default="ton", max_length=20)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("recorded_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-recorded_on", "commodity"],
                "indexes": [
                    models.Index(
                        fields=["commodity", "country", "recorded_on"],
                        name="marketprice_commodi_380814_idx",
                    )
                ],
            },
        ),
    ]
