# Generated by Django 5.2.8 on 2026-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketprices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketprice",
            name="category",
            field=models.CharField(
                choices=[
                    ("crop", "Crop"),
                    ("livestock", "Livestock"),
                    ("input", "Input"),
                ],
                default="crop",
                max_length=20,
            ),
        ),
    ]
