# Generated by Django 5.2.9 on 2025-12-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0004_alter_environmentaldata_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('crop', 'Crop Harvest'), ('animal', 'Animal Product')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms (kg)'), ('liters', 'Liters'), ('crates', 'Crates'), ('bags', 'Bags (90kg)'), ('tons', 'Tons'), ('pieces', 'Pieces')], default='kg', max_length=20)),
                ('collection_date', models.DateField()),
                ('quality_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_collections', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Produce Collection',
                'verbose_name_plural': 'Produce Collections',
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
    ]
