# Generated by Django 5.2.9 on 2025-12-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producecollection',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='producecollection',
            name='storage_location',
        ),
    ]
