# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_advertisement_storereview_productreview_paymentcard'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='marketplace.product'),
        ),
    ]
