# Generated by Django 5.2.9 on 2025-12-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_conversationparticipant_conversation'),
        ('communications', '0002_conversation_product'),
    ]

    operations = [
    ]
