# Generated by Django 5.2.8 on 2025-12-21 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("livestock", "0002_remove_livestockunit_animal_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="livestock.animal",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="inventory",
            name="item_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="inventory",
            name="livestock_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="livestock.livestockunit",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="value_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.DeleteModel(
            name="ProductionRecord",
        ),
    ]
