# Generated by Django 5.2.9 on 2025-12-13 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('produce', '0002_remove_producecollection_estimated_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_products', to='produce.producecollection'),
        ),
    ]
