# Generated by Django 5.2.9 on 2025-12-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_source_produce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.AddField(
            model_name='store',
            name='countries_of_operation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
