# Generated by Django 5.2.9 on 2025-12-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='countries_of_operation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
