# Generated by Django 5.2.9 on 2025-12-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_store_countries_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
