# Generated by Django 5.2.9 on 2025-12-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_advertisement_storereview_productreview_paymentcard'),
        ('marketplace', '0006_store_description'),
    ]

    operations = [
    ]
