# Generated by Django 5.2.9 on 2026-06-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_order_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="store_banners/"),
        ),
        migrations.AddField(
            model_name="store",
            name="business_hours",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="store",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="store_logos/"),
        ),
        migrations.AddField(
            model_name="store",
            name="policies",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="store",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
