# Generated by Django 5.2.8 on 2025-12-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_alter_environmentaldata_additional_info_and_more"),
        ("livestock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestockunit",
            name="animal_type",
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="average_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="housing",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="installation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="purpose",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="queen_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="species",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual Animal"),
                    ("herd", "Herd"),
                    ("batch", "Batch/Stock"),
                    ("colony", "Colony/Hive"),
                    ("population", "Population/Culture"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="age_group",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="animal",
            name="livestock_unit",
            field=models.ForeignKey(
                limit_choices_to={"unit_type": "individual"},
                on_delete=django.db.models.deletion.CASCADE,
                to="livestock.livestockunit",
            ),
        ),
        migrations.AlterField(
            model_name="livestockunit",
            name="breed",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="livestockunit",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="farms.field",
            ),
        ),
        migrations.AlterField(
            model_name="livestockunit",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LivestockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("health", "Health Event"),
                            ("breeding", "Breeding Event"),
                            ("movement", "Movement"),
                            ("mortality", "Mortality"),
                            ("treatment", "Treatment"),
                            ("inspection", "Inspection"),
                            ("feeding", "Feeding"),
                            ("harvest", "Harvest"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "livestock_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livestock.livestockunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("record_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "livestock_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestock_production_records",
                        to="livestock.livestockunit",
                    ),
                ),
            ],
        ),
    ]
