# Generated by Django 5.2.8 on 2025-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0002_remove_livestockunit_animal_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestockunit",
            name="produce_frequency",
            field=models.CharField(
                blank=True,
                help_text="Frequency: Per Day, Per Week, etc.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="produce_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantity per frequency",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="produce_type",
            field=models.CharField(
                blank=True,
                help_text="Type of produce, e.g. Milk, Eggs, Honey",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="livestockunit",
            name="produce_unit",
            field=models.CharField(
                blank=True,
                help_text="Unit, e.g. liters, kg, pieces",
                max_length=20,
                null=True,
            ),
        ),
    ]
