# Generated by Django 5.2.8 on 2025-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0003_livestockunit_produce_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestockunit",
            name="sub_units",
            field=models.JSONField(
                blank=True,
                help_text="List of sub-units with count, age_range, stage, etc.",
                null=True,
            ),
        ),
    ]
