# Generated by Django 5.2.8 on 2025-12-21 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0004_livestockunit_sub_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestockunit",
            name="purpose",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                default=list,
                help_text='List of purposes, e.g. ["meat", "milk"]',
                size=None,
            ),
        ),
    ]
